#!/bin/bash

current_date=$(date +"%Y_%m_%d_%H_%M_%S")
mkdir ~/test && echo "catalog test was created successfully" > ~/report.tmp && touch ~/test/$current_date.tmp
ping -c 1 www.net_nikogo.ru > /dev/null 2>&1 || \
echo "$(date +"%Y-%m-%d %H:%M:%S") Error: Host www.net_nikogo.ru is unreachable" >> ~/report

